### PR TITLE
Update domLink.py

### PR DESCRIPTION
**Pull request by whoot**
Fixes Issue #12

### CODE REVIEW

**Comment by vysecurity** [comment]
I'll fix conflicts later on :|

**Comment by jaywon** [comment]
Any update on getting this merged?

**Comment by vysecurity** [comment]
If someone fixes conflicts I’ll review.

**Comment by jaywon** [comment]
Can't access initial repository (@whoot)  so copied changes and submitted with no merge conflicts on PR #18

**Pull request closed without merging**
