### PR TITLE
re-write

### PR DESCRIPTION
**Pull request by b4ldr**
hi vysec, i saw your code come up on my twitter feed and had been recently thinking of writing a similar tool so thought i would give yours a look.  however i was unable to get your code working quickly and have now almost entirely re-written it.  Its possible i was missing something obvious with your code but i thought i would give you sight of mine in case you a curious.

### CODE REVIEW

**Comment by vysecurity** [comment]
I gotta say, that's pretty legendary. :D

**Comment by vysecurity** [comment]
It's good code. I'm willing to accept as a PR. Though the recursion needs some help, it can end up with prompting you forever with issues. Also, it's currently adding the "non-accepted" organizations and domains to the final output.

If you're checking all the domains manually there's like 100s, then it can take you ages. I left -E -C flags on but the -D is intolerable.

**Comment by vysecurity** [comment]
Also, doesn't seem to write to disk? :P - nevermind, I added it. But just need to fix the blacklisting now.

**Comment by vysecurity** [comment]
Even when I click no, it still puts the organization name into "organisations" :S

**Comment by b4ldr** [comment]
@vysec i did not realise that you wanted the orgs/domains/email etc removed from the output i thought you just wanted them excluded from the recursive search.  I have updated to remove them from the output.  have also added writing of the file

As to the issues with recursion are you able to send something that can recreate it?  however keep in mind i only have a free api account on whoxy.

**Comment by vysecurity** [comment]
Eg. IF the organisation becomes something like "WHOIS COMPANY", then it does a reverse on WHOIS domain. etc... or there's "COMPANY 1", "COMPANY 2" .. "COMPANY 500", don't really wanna click through them all. But so far with my testing, it works OK :D  

I tried to remove the non accepted emails and organizations and domains out of the code, but doesn't seem to work :S

**Comment by vysecurity** [comment]
If you can sort that out for me, I've got some minor changes then I think we can get this pulled, we should also add some credits to you for massively helping out refactoring (I know I'm bad at coding :D) and push it to version 1.1.

**Comment by b4ldr** [comment]
@vysec have you pulled in my most recent changes specifically with theses bits https://github.com/vysec/DomLink/pull/6/files#diff-c14827df5c8fb20738af4e8c9baa186fR196.

As to recursion i don't think it will get in a stuck loop however its definitely possible that you may be prompted a lot for some things.  there are a few ways to make that a bit easier.
  * normalise the company name e.g. lower case it and strip some chars
  * add a filter for company names,  emails, domains which should automatically get blacklisted

**Comment by vysecurity** [comment]
Well, there's a conflict and Idk how to use git properly, so I ended up merging it somehow or another. Let me fill in some credits for you then close this off.

**Comment by b4ldr** [comment]
enjoy and dont worry to much about the credits it shows up in the git log regardless.  have fun hacking ;)

**Pull request closed without merging**
